Repository SeattleColleges/SeattleColleges.github.io, pull requests merged in 2024-06, with the labels that each got.

#49 SeattleColleges.github.io_6_10_update_student_info
  src/students.json
Labels: Sprint 6

#47 SeattleColleges.github.io_7_41_Fix_GitHub_Deployment
  package-lock.json
  package.json
  src/App.js
  src/pages/Contact.js
Labels: bug, Sprint 7

#48 SeattleColleges_7_3_collect_project_info
  src/images/projects/belindas_closet/home_page_dark.png
  src/images/projects/belindas_closet/home_page_light.png
  src/images/projects/belindas_closet/product_page_with_dropdown_dark.png
  src/images/projects/belindas_closet/product_page_with_dropdown_light.png
  src/images/projects/belindas_closet/sign_in_page_dark.png
  src/images/projects/belindas_closet/sign_in_page_light.png
  src/images/projects/belindas_closet/sign_up_page_dark.png
  src/images/projects/belindas_closet/sign_up_page_light.png
  src/images/projects/nsc_events/archived_events_admins_and_creators.png
  src/images/projects/nsc_events/change_password_page.png
  src/images/projects/nsc_events/create_event_page_bottom.png
  src/images/projects/nsc_events/create_event_page_middle.png
  src/images/projects/nsc_events/create_event_page_top.png
  src/images/projects/nsc_events/dashboard_page_admin.png
  src/images/projects/nsc_events/dashboard_page_creators.png
  src/images/projects/nsc_events/edit_user_role_page_admins.png
  src/images/projects/nsc_events/event_detail_page_admin_creator.png
  src/images/projects/nsc_events/event_detail_page_background_mockup.png
  src/images/projects/nsc_events/event_detail_page_not_signed_in.png
  src/images/projects/nsc_events/forgot_password_page.png
  src/images/projects/nsc_events/home_page_not_signed_in.png
  src/images/projects/nsc_events/home_page_not_signed_in_scrolled.png
  src/images/projects/nsc_events/home_page_signed_in_as_admin.png
  src/images/projects/nsc_events/home_page_signed_in_as_user.png
  src/images/projects/nsc_events/load_more_events_mockup.png
  src/images/projects/nsc_events/sign_in_page.png
  src/images/projects/nsc_events/sign_up_page.png
  src/images/projects/nsc_events/view_my_events_page_admin_and_creators.png
  src/projects.json
Labels: enhancement

#55 SeattleColleges.github.io_7_#46_integrate-about-us-blurb
  src/pages/About.js
Labels: enhancement, Sprint 7, USER STORY

#57 SeattleColleges.github.io_6_10_update_student_info_2
  src/images/students/Elida-Ribeiro-de-Souza.png
  src/students.json
Labels: Sprint 6

#65 SeattleColleges.github.io_8_52_Footer_Component_Integration
  src/components/Footer.js
  src/components/microComponents/contact/form.js
  src/pages/Contact.js
  src/pages/Main.js
  src/pages/PortfolioPage.js
  src/pages/StudentsPage.js
Labels: enhancement, Sprint 8
