Repository SeattleColleges/SeattleColleges.github.io, pull requests merged in 2024-05, with the labels that each got.

#20 SeattleColleges.github.io_6_19_placeholder-about-page
  src/App.js
  src/pages/About.js
Labels: enhancement, Sprint 6

#25 SeattleColleges.github.io_6_24_placeholder_contact_page
  src/App.js
  src/pages/Contact.js
Labels: enhancement, Sprint 6

#17 practicum_6_13_navbar-component
  src/components/Navbar.js
  src/images/nsc-app-dev-color.png
  src/index.css
  src/pages/Main.js
Labels: enhancement

#27 SeattleColleges.github.io_6_26_portifolio-page
  App.js
  PlaceholderPage.js
  src/App.js
  src/components/Navbar.js
  src/components/Project.js
  src/pages/PortfolioPage.js
Labels: Sprint 6

#29 SeattleColleges.github.io_6_28_student-page
  App.js
  PlaceholderPage.js
  src/App.js
  src/components/Navbar.js
  src/components/Student.js
  src/pages/StudentsPage.js
Labels: Sprint 6

#44 SeattleColleges.github.io_7_42_Design-About-Us
  src/images/about/NSC_Marquee.jpg
  src/pages/About.js
Labels: enhancement, Sprint 7
